SELECT TOP (1000) [order_uuid]
      ,[picking_sla]
      ,[picking_app_timestamps]
      ,[route_uuid]
      ,[order_last_status]
      ,[delivery_method]
      ,[merchant_frn_id]
      ,[merchant_commercial_group]
      ,[driver_modal_cluster]
      ,[timestamp_local_order_created]
      ,[timestamp_local_assign]
      ,[timestamp_local_accept]
      ,[timestamp_local_to_origin]
      ,[timestamp_local_at_origin]
      ,[timestamp_local_collect]
      ,[timestamp_local_to_destination]
      ,[timestamp_local_at_destination]
      ,[timestamp_local_complete]
      ,[timestamp_local_expected]
      ,[timestamp_local_delivery_time_window_start]
  FROM [Portifólio Linkedin].[dbo].[table_ops]
